### ISSUE TITLE
where is ./models/download_models.sh ?

### ISSUE THREAD

**Issue by joyousrabbit** [pathak22/noreward-rl#2] opened 2017-05-18 08:42 UTC
Hello, it's a great work. But where is ./models/download_models.sh ?

**Comment by ghost** [comment] 2017-05-18 16:13
I guess it will be released after the NIPs deadline, which is 19 May 2017, 1 p.m. Los Angeles time

**Comment by ghost** [comment] 2017-05-21 11:01
Hmm ... I was really looking forward to this:(

**Comment by pathak22** [comment] 2017-05-22 11:33
@joyousrabbit @AjayTalati Thanks a lot for your interest. I have now pushed the demo code to github. Please take a look. I apologize for the delay due to NIPS deadline. Thanks !!

**Comment by ghost** [comment] 2017-05-22 13:18
Hi @pathak22, thank you very much for pushing the demo code.

For some reason I'm having lots of problems installing `ppaquette-gym-doom` at the moment? 

I'm really looking forward to the training code though, in particular the `Intrinsic Curiosity Module`, I guess it will be possible to train an agent which uses it on any OpenAI gym environment? So there's no need to worry about getting `doom` working at the moment? 

Thanks very much :+1:

**Comment by chikiuso** [comment] 2017-05-22 16:25
Any chance the super mario bros model will be released?

**Comment by ghost** [comment] 2017-05-27 08:45
Hi @pathak22, is there any chance you can give us an update when the training code with the `ICM` module will be released?

Thanks a lot :+1:

**Comment by pathak22** [comment] 2017-05-27 21:18
@chikiuso I will try to release the Mario model this week. The reason I didn't release it the first time as I could not figure out the easiest way to release all the dependencies from different sources/Licenses.

@AjayTalati The main reason that is holding the code release is finding best way to package dependencies and LICENSES of their sources. I am working on cleaning it up to minimize the dependencies (and I was on a break this last week). I will try my best to release it in a week or two. Thanks a lot for the interest, and sorry for the delay !

**Comment by ghost** [comment] 2017-05-27 21:56
Hi @pathak22, thanks very much for the reply. 

I'm mainly interested in the `ICM` module just to understand your paper better, and to do really simple experiments on MDPs, (gridworld's, bandits and the like, nothing complicated like Mario). 

Your papers really interesting, because it's human like, and I'm interested in novel ways of implementing predictive coding type architectures, and comparing the `ICM` module with variational methods, e.g. [VIME](https://github.com/openai/vime).

Please take your time, and I look forward to learning from the code when you get the chance to release it.

All the best, Ajay

**Comment by sunshineclt** [comment] 2017-06-28 03:28
Looking forward to learning from your training code +1 😃

**Comment by pathak22** [comment] 2017-07-11 09:19
@sunshineclt @AjayTalati @joyousrabbit 

I have finally released the full training code. This comes with the scripts to train on VizDoom and Super Mario Bros., scripts to do inference and scripts to customize VizDoom environment for RL experiments. The wrappers which allow for faster training in Mario and Doom have also been released. 

Hopefully, the code will be useful to you for reproducing our work and even beyond to develop new algorithms and experiments. Sorry for long delay in doing so and thank you for your patience. Looking forward to how it turns out! :)

**Closed as completed by pathak22** 2017-07-11 09:19 UTC
